

CREATE TABLE CUSTOMER
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    mail VARCHAR(255)
);

CREATE TABLE TRACKING_INFO
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255),
    location VARCHAR(255)
);

CREATE TABLE ORDERS
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    tracking_info_id INT,
    order_date DATE
);